### ISSUE TITLE
Can you provide us with the datasets used in the project, or how to create them?

### ISSUE THREAD

**Issue by cookiegg** [xl402/Deep-Koopman#1]
Thank you for making this project, I'm very interested in this project. When I run the code, I find that the dataset is missing, can you provide a dataset or a way to create one?  Thanks a lot!

**Comment by xl402** [comment]
Hi, thanks for your interest, and apologies for the terrible code quality
(looking back there are a lot of things I could have done better). Anyway,
I have uploaded the data directory to master. All the data is simply
generated. May I ask how come you are interested in Koopman? Thanks.

Tom

**Comment by cookiegg** [comment]
I am trying to apply the Koopman operator to nonlinear system control problems.
I think that the Koopman operator provides an efficient way to represent the global linearization of nonlinear systems. It is also more interpretable than end-to-end methods, such as using neural networks to learn control strategies directly. 

But I am still just a newbie to the Koopman operator method, and no one else around is interested in this field. I hope I can discuss this with you more in the future. Thanks a lot.
